version: "3"
services:
  db:
    image: postgres:latest
    container_name: "${DB_CONTAINER_NAME}"
    # restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      #   - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./db_data:/var/lib/postgresql/data
  app:
    # image: node:16.13.1
    build: ./bowling-app
    container_name: nestjs
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - /home/gon2gon2/git/bowling-nest/bowling-app:/bowling-app
# networks:
#   backend:
# volumes:
#   db_data:
